Breves adaptações
lottec-ufpb/paratodxs pull request #5
Opened 2023-04-21 20:03 UTC by OliveiraHermogenes

O impulso das adaptações foi, em primeiro lugar, remover demarcação territorial na filosofia, afinal lecionamos a matéria para outros cursos, e, em segundo lugar, buscar introduzir uma distinção entre fórmula e sentença, a começar aqui do prefácio.

2023-04-24 17:01 UTC, diegofernandess requested changes

2023-09-25 11:34 UTC, OliveiraHermogenes commented on forallx-yyc-preface.tex
> +Para estas linguagens formais é possível definir rigorosamente quando uma fórmula se segue ou não de outras.
Que tal, na linhas 5: "...isto é, um simbolismo no qual as expressões bem formadas da linguagem, as fórmulas, são precisamente definidas."

2023-09-25 11:39 UTC, OliveiraHermogenes commented on forallx-yyc-preface.tex
> +Para estas linguagens formais é possível definir rigorosamente quando uma fórmula se segue ou não de outras.
Como se trata do prefácio, talvez seja melhor não entrar em detalhes. Fiz alterações depois de forma a manter a discussão no âmbito da consequência lógica sem mencionar explicitamente as fórmulas.

2024-01-13 16:23 UTC, diegofernandess approved these changes
Concordo agora com a reformulação.

2024-01-13 16:51 UTC, merged